// 21efe3b67b3df759cbb0b0273d909f1d49829
//
// This file was automatically generated by the
// updaterevision tool. Do not edit by hand.

#define GIT_DESCRIPTION "2.7.1"
#define GIT_HASH "21efe3b67b3df759cbb0b0273d909f1d49829"
#define GIT_TIME "2013-07-02 15:47:49 -0500"
